# .github/workflows/build-macos.yml

name: Build macOS App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Download and extract Oracle Instant Client for macOS
        run: |
          curl -o instantclient.zip https://download.oracle.com/otn_software/mac/instantclient/198000/instantclient-basic-macos.x64-19.8.0.0.0dbru.zip
          unzip instantclient.zip
          echo "$PWD/instantclient_19_8" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller --name "도서회원관리" --onefile --windowed book_mainpage.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: 도서회원관리-macOS
          path: dist/도서회원관리.app
